# Generated by Django 6.0.6 on 2026-06-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_class_classroom_educator_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
