# Generated by Django 6.0.6 on 2026-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_class_user_classroom_user_day_user_educator_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draf"), ("done", "Selesai")], default="draft"
            ),
        ),
    ]
