# Generated by Django 6.0.6 on 2026-07-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_scheduledata"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledata",
            name="classroom_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="blog.classroom",
            ),
        ),
        migrations.AddField(
            model_name="scheduledata",
            name="educator_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="blog.educator",
            ),
        ),
        migrations.AddField(
            model_name="scheduledata",
            name="lesson_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="blog.lesson",
            ),
        ),
    ]
