# Generated by Django 6.0.6 on 2026-07-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_scheduledata_classroom_id_scheduledata_educator_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledata",
            name="lesson_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="blog.lesson",
            ),
        ),
    ]
