# Generated by Django 6.0.6 on 2026-07-19 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_scheduledata_classroom_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledata",
            name="classroom_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="blog.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledata",
            name="educator_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="blog.educator",
            ),
        ),
    ]
