# Generated by Django 6.0.6 on 2026-07-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_scheduledata_classroom_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduledata",
            old_name="class_id",
            new_name="classes",
        ),
        migrations.RenameField(
            model_name="scheduledata",
            old_name="classroom_id",
            new_name="classroom",
        ),
        migrations.RenameField(
            model_name="scheduledata",
            old_name="day_id",
            new_name="day",
        ),
        migrations.RenameField(
            model_name="scheduledata",
            old_name="educator_id",
            new_name="educator",
        ),
        migrations.RenameField(
            model_name="scheduledata",
            old_name="lesson_id",
            new_name="lesson",
        ),
        migrations.RenameField(
            model_name="scheduledata",
            old_name="lesson_hour_id",
            new_name="lesson_hour",
        ),
    ]
