# Generated by Django 6.0.6 on 2026-07-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_scheduledata_time_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="class_capacity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="time_slot",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
