# Generated by Django 6.0.6 on 2026-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_classroom_class_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="class_capacity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Kapasitas Kelas"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="time_slot",
            field=models.PositiveIntegerField(default=1, verbose_name="Slot Waktu"),
        ),
    ]
