# Generated by Django 6.0.6 on 2026-06-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("finish_time", models.TimeField()),
                ("sequence", models.IntegerField(default=1)),
                ("is_break", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
