# Generated by Django 6.0.6 on 2026-07-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_schedule_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("hari", "Hari"),
                            ("jam_pembelajaran", "Jam Pembelajaran"),
                            ("kelas", "Kelas"),
                            ("ruang_kelas", "Ruang Kelas"),
                            ("pengajar", "Pengajar"),
                            ("pelajaran", "Pelajaran"),
                        ]
                    ),
                ),
                ("entity_id", models.IntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="blog.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Constraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_capable", models.BooleanField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="blog.schedule",
                    ),
                ),
                (
                    "data1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="blog.data",
                    ),
                ),
                (
                    "data2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="blog.data",
                    ),
                ),
            ],
        ),
    ]
