# Generated by Django 6.0.6 on 2026-07-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_rename_class_id_scheduledata_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledata",
            name="time_slot",
            field=models.IntegerField(default=1),
        ),
    ]
